# Eigenvalues & Eigenvectors

In [1]:
import numpy as np

In [2]:
M = np.array(
    [
        [47,13,-34],
        [-41,4,0],
        [28,58,41]
    ]
)

In [3]:
def get_eigenvals(M):
    return np.linalg.eigvals(M)

In [4]:
get_eigenvals(M)

array([15.50432174+40.4024353j, 15.50432174-40.4024353j,
       60.99135652 +0.j       ])

In [5]:
def get_eigenvectors(M):
    w, v = np.linalg.eig(M)
    return v

In [6]:
vectors = get_eigenvectors(M)
# get all 3 eigenvectors
vectors[:,0].reshape(3,1)

array([[ 0.38685899+0.38932426j],
       [-0.4688532 +0.25907796j],
       [ 0.64173362+0.j        ]])

In [7]:
vectors[:,1].reshape(3,1)

array([[ 0.38685899-0.38932426j],
       [-0.4688532 -0.25907796j],
       [ 0.64173362-0.j        ]])

In [8]:
vectors[:,2].reshape(3,1)

array([[-0.70907074+0.j],
       [ 0.5101107 +0.j],
       [ 0.48683237+0.j]])